### PR TITLE
Fix dicom reader to merge dicom slices

### PR DESCRIPTION
**Pull request by floryst**
Also fix guard check on reader existence in ReaderFactory.

### CODE REVIEW

**Comment by jourdain** [comment]
seems ok, but don't know

**Comment by floryst** [comment]
This at least fixes the raw file load issue. The DICOM stuff works but I may tweak/refine the interface.

**Comment by jourdain** [comment]
cool thx. What was the deal?

**Comment by floryst** [comment]
https://github.com/Kitware/paraview-glance/pull/226/files#diff-0685cf42d9c2f170eef4fccbbfc61511L168

**Comment by jourdain** [comment]
hum, ok so I broke it... ;-)

**Comment by floryst** [comment]
Haha, well what matters is that it's fixed now :) (whenever I decide the dicom stuff is good to merge)

**Comment by jourdain** [comment]
Yeah that's perfect.

**Pull request merged**
