### PR TITLE
feat: Add animation controls

### PR DESCRIPTION
**Pull request by boucaud**
* Integrates the AnimationProxyManager into Paraview-Glance
* Adds animation controls to the global tab of the drawer

### CODE REVIEW

**Comment by boucaud** [comment]
@floryst WDYT ?

**Comment by boucaud** [comment]
Screenshot: 
DeepinScreenshot_select-area_20210416160455

Testing data: https://github.com/Kitware/vtk-js-datasets/blob/master/data/vtkjs/timesteps.vtkjs

**Comment by floryst** [comment]
I like it! One UI suggestion: add `flat` to the control buttons, and add `align-axis: center` to the `.wrapper` style so that the controls are centered.

If you delete the dataset, do the animation controls disable?

**Comment by boucaud** [comment]
> I like it! One UI suggestion: add `flat` to the control buttons, and add `align-axis: center` to the `.wrapper` style so that the controls are centered.

Done

DeepinScreenshot_select-area_20210416162038


> If you delete the dataset, do the animation controls disable?

In general, the controls are not shown if no animation is available.

However, in the case of a .vtkjs scene with an animation, the whole scene can be animated, including cameras, background color, etc... So the animation makes sense even with no dataset remaining.

Do you think it would be better to completely remove the animation, if one of the scene's datasets was removed ?

**Comment by floryst** [comment]
Nice! Also, I just remembered that `flat` was the old name. It should be `text` instead. And maybe if it doesn't mess up the look and feel you can add `icon` as well to the button properties? Just an option.

I think that so long as there is something that can animate, you should keep the controls available.

**Comment by boucaud** [comment]
> Nice! Also, I just remembered that `flat` was the old name. It should be `text` instead. And maybe if it doesn't mess up the look and feel you can add `icon` as well to the button properties? Just an option.

Indeed, that looks better with `text`. I felt that the round look `icon` provides looks strange for a button row, though.

> I think that so long as there is something that can animate, you should keep the controls available.
 
Then it should be good as-is.

**Comment by floryst** [comment]
LGTM! I'll merge this.

**Comment by boucaud** [comment]
I think it's ready, unless you see something else

**Comment by floryst** [comment]
@boucaud can you make a new PR that updates the package-lock.json? This PR didn't update that, so travis is complaining.

**Pull request merged**
