### PR TITLE
Save opacity and don't reset camera on state load

### LINKED ISSUE #346: Change default views/transparency/etc of vtkjs/html exported from ParaView
**My goal of using Glance**: Share interactive 3d visualization
**How I use Glance**: Use the "Export Scene" feature of ParaView + Open the generated vtkjs/html file in a ParaViewGlance browser
**The Issue I have**: Can I force some of the default behaviours of the generated vtkjs file?
**My experience with Glance**: New user

__Example behaviours I want to force__:
1. The default camera seemed to be reset so that the view looks really small in the Glance browser compared to that in a ParaView window
2. Certain information like the transparency of plane slices is lost.
3. Colorbar is not shown.

I tried to use the "Save State" feature of ParaViewGlance, but that takes forever to finish (the vtkjs is ~50MB).

Thank you for your suggestions.

### PR DESCRIPTION
**Pull request by floryst**
Fixes #346 
- Opacity is now saved in state files
- Removed extraneous camera reset
- Guard against null source change

### CODE REVIEW

**Comment by floryst** [comment]
@liangwang0734 It would be great if you could test out these changes (especially the camera changes) before I merge so I can catch any issues that may arise.

**Comment by liangwang0734** [comment]
@floryst I confirm that #347 fixes the lost transparency issue.

**Comment by liangwang0734** [comment]
@floryst Sorry I forgot to mention that the camera reset issue is also fixed. Thanks for working on these.

**Comment by liangwang0734** [comment]
@floryst Would you confirm if the following are the correct way to test? Sorry, I'm not familiar with Glance/js:
```
$ git log |head
commit be39f8aef853db71763ef80e272a6c4108ff42c2
Author: Forrest Li <forrest.li@kitware.com>
Date:   Mon Jul 27 10:54:13 2020 -0400

    fix(VtkView): Guard against null source
$ npm install
$ npm run build
$ npm run dev

> paraview-glance@0.0.0-semantically-release dev /home/liang/src/paraview-glance
> webpack-dev-server --config build/webpack.dev.config.js

ℹ ｢wds｣: Project is running at http://0.0.0.0:9999/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/liang/src/paraview-glance/dist
ℹ ｢wdm｣: wait until bundle finished: /
```

After steps above, I went to http://0.0.0.0:9999/ and loaded my vtkjs files exported from ParaView.

- The cameras are still reset, whatever the camera parameters are in the source ParaView window is.
- The transparency is correct.

**Comment by floryst** [comment]
Yep! Great, I'll merge to master.

**Pull request merged**
