### PR TITLE
feat(GlanceVtkJsReader): Add support for volume import from .vtkjs

### PR DESCRIPTION
**Pull request by boucaud**
Note: waiting on https://github.com/Kitware/vtk-js/pull/1629

This would allow Paraview-Glance to load .vtk-js files containg volumes that were exported from VTK or ParaView (see https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7409 and https://gitlab.kitware.com/paraview/paraview/-/merge_requests/4531)

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM

**Comment by floryst** [comment]
This looks good to me. Once there's a PR for bumping the vtk.js version, we can merge.

**Comment by boucaud** [comment]
There seems to be an issue (build errors) between vtk-js versions 14.19.0 and 15.0.0. I didn't have time to look into it further today.

**Comment by jourdain** [comment]
Remove your /node_modules and run `npm install`

**Comment by floryst** [comment]
Oh actually you raise a good point. At minimum, part of the issue is due to vuetify-loader not yet working with webpack 5.

**Comment by boucaud** [comment]
@floryst do you have any news on this ?

**Comment by floryst** [comment]
I can re-visit this. I'll get back to you shortly after I see what is needed for updating.

**Comment by boucaud** [comment]
Note: I'll integrate https://github.com/Kitware/vtk-js/pull/1659/ here as well

**Comment by floryst** [comment]
#382 is merged, so let me know when this PR is ready and I'll merge.

**Comment by boucaud** [comment]
> #382 is merged, so let me know when this PR is ready and I'll merge.

I just tested it, it can be merged.

**Pull request merged**
