### PR TITLE
feat(App): Support opening files with Ctrl/Cmd+O (and discussion on other shortcuts)

### PR DESCRIPTION
**Pull request by floryst**
What other keyboard shortcuts do we want?

We also will need to have a sheet of supported keyboard shortcuts.

### CODE REVIEW

**Comment by jourdain** [comment]
Open File
Delete (active source)
Screenshot (active view)
Toggle side bar
Collapse/Expend all datasets
Collapse/Expend dataset controls
Switch active view to X,Y,Z,3D (ctrl+x/y/z/1) ?
Reset camera (R) 
Rotate 90 (ctrl+ leftArrow/rightArrow)
Split / unsplit (ctr+[+]/[-])

anything else?

**Comment by jourdain** [comment]
Let's make a shortcut page on the web site along with basic guide.

**Comment by floryst** [comment]
@aylward's suggestion: shortcuts for scrolling through image slice (e.g. no touchpad or scroll wheel, and don't want to use sliders)

**Comment by floryst** [comment]
What is considered to be the "active source" or "active view"? For multiple sources/views, there is no visual indication for either of these concepts.

**Comment by jourdain** [comment]
I agree that the "active" part is trickier than before. 
The active view is the view that was visited last with the mouse (or the one still below the mouse).

For the active source, it will be the last one created. (Hopefully only one is loaded.) Or we need a toggle on the dataset header itself to activate it...

**Comment by aylward** [comment]
Perhaps we need to consider the object list more carefully...layout and
functionality.

---
Sent via phone.

**Comment by jourdain** [comment]
I think it was managed in the jumbo one...

**Pull request closed without merging**
