### PR TITLE
fix(ColorBy): Use workaround for array names with single colons

### PR DESCRIPTION
**Pull request by floryst**
Reference bug: https://discourse.vtk.org/t/paraview-glance-no-color-mapping-when-data-array-name-contains-colon/2022
@jourdain

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM maybe you could have created a `const SEPERATOR` at the top of the file instead. ;-)

**Comment by floryst** [comment]
I considered using `const SEPARATOR` but I decided to do this so I can minimize any weird merge conflicts with my branches. It'll look nicer soon. :)

**Comment by jourdain** [comment]
Then go for it, merge when you want...

**Pull request merged**
