### PR TITLE
feat(PaintTool): Add paint tool to Glance

### PR DESCRIPTION
**Pull request by floryst**
Adds painting to Glance. 
- painting labelmaps
- opacity for labelmaps
- undo/redo

### CODE REVIEW

**Comment by jcfr** [comment]
Issue with drawing:
(1) Go to http://forrestli.com/glance/
(2) Load Head.mha
(3) Click on "split view"
(4) Select Tools,  select "Master Volume"
(5) Create a new label map
(6) Add label
(7) starts painting

image

**Comment by floryst** [comment]
Thanks for the report! I also discovered this and am working on a fix. Painting does happen, but it occurs in the wrong slice.

**Comment by floryst** [comment]
Fixed!

**Comment by jcfr** [comment]
Strange ... I am observing the same behavior. Let me know when the updated version is deployed.

**Comment by floryst** [comment]
Try again? I deployed an updated version again.

**Comment by aylward** [comment]
Color changes in other strokes on undo.

Paint in one color (call it color A)
Undo/redo
Paint in another color (call it color B)
Undo - and the last stroke in changes to color B

Also, paint, undo, switch color, paint, undo - and original stroke returns.

**Comment by floryst** [comment]
Can't seem to reproduce the above issue.

**Pull request merged**
