### PR TITLE
Allow returning to landing page

### PR DESCRIPTION
**Pull request by floryst**
Clicking the logo will return to landing page, and a button will pop up allowing you to return to the app from the landing page.

I'm thinking of also adding browser history hooks so back/forward works for this as well.

@agirault

### CODE REVIEW

**Comment by agirault** [comment]
Does clicking the logo bring you back to the landing page without a warning so you don't lose your progress? Or is that what you meant by the popup?

**Comment by floryst** [comment]
You don't lose any work by going back to the landing page, but there isn't any indication that data would be saved if you do go back.

This is what you see right now when hovering over the logo when you are in the app view. Not the most obvious control, but similar to how clicking on a website's header will navigate you back to the homepage.

image

This is what you see when you have switched back to the landing view:

image

**Comment by agirault** [comment]
Oh I see, so even though you are back to the landing page, you're data and state is still around?

**Comment by floryst** [comment]
Yep. And loading sample data or your own data from the landing page will add to your existing datasets.

**Comment by floryst** [comment]
I've removed the "back to app" button, and opted for just the logo. Browser buttons (back/forward) now work to bring you back to landing or the app.

**Pull request merged**
